CREATE TABLE IF NOT EXISTS supplier (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '供应商ID',
  name VARCHAR(100) NOT NULL COMMENT '供应商名称',
  logo VARCHAR(255) NULL COMMENT '供应商logo/封面图',
  images TEXT NULL COMMENT '供应商图片，JSON数组',
  city VARCHAR(100) NULL COMMENT '城市',
  country VARCHAR(50) DEFAULT 'China' COMMENT '国家',
  main_products VARCHAR(255) NULL COMMENT '主营产品',
  moq VARCHAR(100) NULL COMMENT '最低起订量',
  description TEXT NULL COMMENT '简介',
  tags VARCHAR(255) NULL COMMENT '标签，JSON数组，如 Verified Supplier/OEM/Export Experience',
  export_markets VARCHAR(255) NULL COMMENT '出口市场，如 Philippines, Malaysia',
  year_established VARCHAR(20) NULL COMMENT '成立年份',
  contact_name VARCHAR(100) NULL COMMENT '联系人',
  contact_whatsapp VARCHAR(100) NULL COMMENT 'WhatsApp',
  contact_wechat VARCHAR(100) NULL COMMENT '微信',
  contact_phone VARCHAR(100) NULL COMMENT '电话',
  contact_email VARCHAR(100) NULL COMMENT '邮箱',
  show_contact TINYINT(1) DEFAULT 0 COMMENT '是否开放联系方式',
  status TINYINT(1) DEFAULT 1 COMMENT '状态：1启用 0禁用',
  sort INT DEFAULT 0 COMMENT '排序',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商表';
